-- Railway Management System database creation --
CREATE DATABASE RailwayManagementSystem;

USE RailwayManagementSystem;
GO

-- Create table for Person
CREATE TABLE Person (
    PERSON_ID INT,
    first_name NVARCHAR(100) NOT NULL,
    last_name NVARCHAR(100),
    email_encrypted VARBINARY(MAX),
    date_of_birth DATE NOT NULL,
    street_name NVARCHAR(255) NOT NULL,
    state NVARCHAR(20) NOT NULL,
    city NVARCHAR(100) NOT NULL,
    zipcode NVARCHAR(20) NOT NULL,
    Person_type CHAR(1) NOT NULL,
    CONSTRAINT PK_Person PRIMARY KEY (PERSON_ID),
    CONSTRAINT CK_Person_Person_type CHECK (Person_type IN ('P', 'E'))
);

-- Create table for Passenger
CREATE TABLE PASSENGER (
    passenger_id INT,
    passenger_accessibility VARCHAR(255),
    CONSTRAINT PK_PASSENGER PRIMARY KEY (passenger_id),
    CONSTRAINT FK_PASSENGER_PERSON FOREIGN KEY (passenger_id) REFERENCES Person(PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for Employee
CREATE TABLE EMPLOYEE (
    employee_id INT,
    date_of_joining DATE,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (employee_id),
    CONSTRAINT FK_EMPLOYEE_PERSON FOREIGN KEY (employee_id) REFERENCES Person(PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for MBTA_CHARLIE
CREATE TABLE MBTA_CHARLIE (
    charlie_id INT,
    passenger_id INT,
    balance DECIMAL(10, 2) NOT NULL CHECK (balance >= 0),
    card_number_encrypted VARBINARY(MAX),
    CONSTRAINT PK_MBTA_CHARLIE PRIMARY KEY (charlie_id),
    CONSTRAINT FK_MBTA_CHARLIE_Passenger FOREIGN KEY (passenger_id) REFERENCES PASSENGER(passenger_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for MBTA_TYPES
CREATE TABLE MBTA_TYPES (
    type_id INT,
    type_name VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MBTA_TYPES PRIMARY KEY (type_id),
    CONSTRAINT CK_MBTA_TYPES_TypeName CHECK (type_name IN ('Blue', 'Green', 'Red', 'Orange', 'Purple'))
);

-- Create table for MBTA_ROUTEINFO
CREATE TABLE MBTA_ROUTEINFO (
    route_id INT,
    route_from VARCHAR(255) NOT NULL,
    route_to VARCHAR(255) NOT NULL,
    duration INT NOT NULL,
    CONSTRAINT PK_MBTA_ROUTEINFO PRIMARY KEY (route_id),
    CONSTRAINT CK_MBTA_ROUTEINFO_Duration CHECK (duration > 0)
);

-- Create table for MBTA_STATION
CREATE TABLE MBTA_STATION (
    station_id INT,
    station_name VARCHAR(255) NOT NULL,
    station_zipcode VARCHAR(10) NOT NULL,
    station_status VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MBTA_STATION PRIMARY KEY (station_id),
    CONSTRAINT CK_MBTA_STATION_Status CHECK (station_status IN ('Active', 'Under Construction', 'Closed'))
);

-- Create table for MBTA_PASSENGERFREQUENCY
CREATE TABLE MBTA_PASSENGERFREQUENCY (
    frequency_id INT,
    station_id INT,
    passenger_id INT,
    avg_sec INT NOT NULL,
    sd_sec INT NOT NULL,
    day_type VARCHAR(50) NOT NULL,
    CONSTRAINT PK_MBTA_PASSENGERFREQUENCY PRIMARY KEY (frequency_id),
    CONSTRAINT FK_MBTA_PASSENGERFREQUENCY_MBTA_STATION FOREIGN KEY (station_id) REFERENCES MBTA_STATION(station_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MBTA_PASSENGERFREQUENCY_Passenger FOREIGN KEY (passenger_id) REFERENCES PASSENGER(passenger_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_MBTA_PASSENGERFREQUENCY_AvgSec CHECK (avg_sec >= 0),
    CONSTRAINT CK_MBTA_PASSENGERFREQUENCY_SdSec CHECK (sd_sec >= 0),
    CONSTRAINT CK_MBTA_PASSENGERFREQUENCY_DayType CHECK (day_type IN ('Weekday', 'Weekend', 'Holiday'))
);

-- Create table for MBTA_TRANSACTION
CREATE TABLE MBTA_TRANSACTION (
    transaction_id INT,
    charlie_id INT,
    amount_encrypted VARBINARY(MAX),
    CONSTRAINT PK_MBTA_TRANSACTION PRIMARY KEY (transaction_id),
    CONSTRAINT FK_MBTA_TRANSACTION_MBTA_CHARLIE FOREIGN KEY (charlie_id) REFERENCES MBTA_CHARLIE(charlie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for MBTA_TRAININFO
CREATE TABLE MBTA_TRAININFO (
    train_id INT,
    train_serial_no VARCHAR(255) NOT NULL,
    year_of_manufacturing DATE NOT NULL,
    last_service_date DATE NOT NULL,
    capacity INT NOT NULL,
    CONSTRAINT PK_MBTA_TRAININFO PRIMARY KEY (train_id),
    CONSTRAINT UQ_MBTA_TRAININFO_TrainSerialNo UNIQUE (train_serial_no),
    CONSTRAINT CK_MBTA_TRAININFO_Capacity CHECK (capacity > 0)
);

-- Create table for EMPLOYEE_TRAIN_ASSIGNMENT
CREATE TABLE EMPLOYEE_TRAIN_ASSIGNMENT (
    emp_train_id INT,
    employee_id INT NOT NULL,
    train_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT PK_EMPLOYEE_TRAIN_ASSIGNMENT PRIMARY KEY (emp_train_id),
    CONSTRAINT FK_EMPLOYEE_TRAIN_ASSIGNMENT_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES EMPLOYEE(employee_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_EMPLOYEE_TRAIN_ASSIGNMENT_MBTA_TRAININFO FOREIGN KEY (train_id) REFERENCES MBTA_TRAININFO(train_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_EMPLOYEE_TRAIN_ASSIGNMENT_Dates CHECK (end_date >= start_date OR end_date IS NULL)
);

-- Create table for TRAIN_STATUS_HISTORY
CREATE TABLE TRAIN_STATUS_HISTORY (
    history_id INT IDENTITY(1,1), -- Auto-incrementing primary key
    train_id INT NOT NULL,
    station_id INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    event_time DATETIME2 NOT NULL, 
    delay_reason NVARCHAR(250),
    CONSTRAINT PK_TRAIN_STATUS_HISTORY PRIMARY KEY (history_id),
    CONSTRAINT FK_TRAIN_STATUS_HISTORY_MBTA_TRAININFO FOREIGN KEY (train_id) REFERENCES MBTA_TRAININFO(train_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TRAIN_STATUS_HISTORY_MBTA_STATION FOREIGN KEY (station_id) REFERENCES MBTA_STATION(station_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_TRAIN_STATUS_HISTORY_Status CHECK (status IN ('On Time', 'Delayed', 'Cancelled', 'Under Maintenance'))
);

-- Create table for MBTA_SCHEDULE
CREATE TABLE MBTA_SCHEDULE (
    schedule_id INT,
    train_id INT NOT NULL,
    arrival_time TIME NOT NULL,
    departure_time TIME NOT NULL,
    CONSTRAINT PK_MBTA_SCHEDULE PRIMARY KEY (schedule_id),
    CONSTRAINT FK_MBTA_SCHEDULE_MBTA_TRAININFO FOREIGN KEY (train_id) REFERENCES MBTA_TRAININFO(train_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_MBTA_SCHEDULE_Times CHECK (departure_time > arrival_time)
);

-- Create table for MBTA_ROUTE_SCHEDULE
CREATE TABLE MBTA_ROUTE_SCHEDULE (
    route_schedule_id INT,
    route_id INT NOT NULL,
    schedule_id INT NOT NULL,
    CONSTRAINT PK_MBTA_ROUTE_SCHEDULE PRIMARY KEY (route_schedule_id),
    CONSTRAINT FK_MBTA_ROUTE_SCHEDULE_MBTA_ROUTEINFO FOREIGN KEY (route_id) REFERENCES MBTA_ROUTEINFO(route_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MBTA_ROUTE_SCHEDULE_MBTA_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES MBTA_SCHEDULE(schedule_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for TRAIN_CURRENTSTATUS
CREATE TABLE TRAIN_CURRENTSTATUS (
    TrainCurrentStatus_ID INT,
    train_id INT NOT NULL,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    status VARCHAR(255) NOT NULL,
    last_update DATETIME NOT NULL,
    CONSTRAINT PK_TRAIN_CURRENTSTATUS PRIMARY KEY (TrainCurrentStatus_ID),
    CONSTRAINT FK_TRAIN_CURRENTSTATUS_MBTA_TRAININFO FOREIGN KEY (train_id) REFERENCES MBTA_TRAININFO(train_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_TRAIN_CURRENTSTATUS_Status CHECK (status IN ('Running', 'Stopped', 'Maintenance'))
);

-- Create table for TRAIN_ROUTEASSIGNMENT
CREATE TABLE TRAIN_ROUTEASSIGNMENT (
    train_route_id INT IDENTITY(1,1),
    train_id INT NOT NULL,
    route_id INT NOT NULL,
    CONSTRAINT PK_TRAIN_ROUTEASSIGNMENT PRIMARY KEY (train_route_id),
    CONSTRAINT FK_TRAIN_ROUTEASSIGNMENT_MBTA_TRAININFO FOREIGN KEY (train_id) REFERENCES MBTA_TRAININFO(train_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TRAIN_ROUTEASSIGNMENT_MBTA_ROUTEINFO FOREIGN KEY (route_id) REFERENCES MBTA_ROUTEINFO(route_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create table for ROUTE_TYPE
CREATE TABLE ROUTE_TYPE (
    route_type_id INT,
    route_id INT NOT NULL,
    type_id INT NOT NULL,
    CONSTRAINT PK_ROUTE_TYPE PRIMARY KEY (route_type_id),
    CONSTRAINT FK_ROUTE_TYPE_MBTA_ROUTEINFO FOREIGN KEY (route_id) REFERENCES MBTA_ROUTEINFO(route_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ROUTE_TYPE_MBTA_TYPES FOREIGN KEY (type_id) REFERENCES MBTA_TYPES(type_id) ON DELETE CASCADE ON UPDATE CASCADE-- Changed to ON DELETE NO ACTION
);

-- Create table for STATION_ROUTE
CREATE TABLE STATION_ROUTE (
    station_route_id INT,
    station_id INT NOT NULL,
    route_id INT NOT NULL,
    CONSTRAINT PK_STATION_ROUTE PRIMARY KEY (station_route_id),
    CONSTRAINT FK_MBTA_PASSENGERFREQUENCY_MBTA_STATION_ROUTE FOREIGN KEY (station_id) REFERENCES MBTA_STATION(station_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ROUTE_TYPE_MBTA_STATION_ROUTEINFO FOREIGN KEY (route_id) REFERENCES MBTA_ROUTEINFO(route_id) ON DELETE CASCADE ON UPDATE CASCADE
);
