-- Non-clustered indices -- 

CREATE NONCLUSTERED INDEX IDX_MBTA_TRANSACTION_CharlieID ON MBTA_TRANSACTION(charlie_id);

CREATE NONCLUSTERED INDEX IDX_MBTA_PASSENGERFREQUENCY_StationDay ON MBTA_PASSENGERFREQUENCY(station_id, day_type);

CREATE NONCLUSTERED INDEX IDX_EMPLOYEE_TRAIN_ASSIGNMENT_EmployeeID ON EMPLOYEE_TRAIN_ASSIGNMENT(employee_id);

CREATE NONCLUSTERED INDEX IDX_TRAIN_STATUS_HISTORY_TrainTimestamp ON TRAIN_STATUS_HISTORY(train_id, event_time);

CREATE NONCLUSTERED INDEX IDX_MBTA_SCHEDULE_RouteTrain ON MBTA_SCHEDULE(train_id);
